# Generated by Django 2.1.15 on 2020-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200228_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='type_of_product',
            field=models.CharField(choices=[('s', 'sauces'), ('f', 'frozen')], default='', max_length=128),
            preserve_default=False,
        ),
    ]
